---
# Server ports
ssh_port: 2222
proxy_port: 8888

# Nginx + SSL
domain: example.com
domain_www: "www.{{ domain }}"
admin_email: "admin@{{ domain }}"

# App user
appuser: yoda

# AmneziaWG VPN
amnezia_port: 39743
amnezia_configs_dir: /root/amnezia_configs
amnezia_client_names:
  - my_phone
  - my_laptop
